### ISSUE TITLE
ask for the compiled pdf file

### ISSUE THREAD

**Issue by amiltonwong** [liangliangdeveloper/Note-of-GAMES101#1]
Hi, @liangliangdeveloper 

Thanks a lot for releasing such useful notes. However, I could not compile tex file successfully. Would you also release the compiled pdf file?

Thanks~

**Comment by liangliangdeveloper** [comment]
You can download it at the release page. Thanks for your concern.

**Comment by amiltonwong** [comment]
Found it. Thanks a lot :)
